### ISSUE TITLE
Pinyin IM needs an option to only offer traditional words

### ISSUE THREAD

**Issue by yurivict** [fcitx/fcitx#283]
The user I installed fcitx for is from Taiwan, and he only feels comfortable using the traditional words, but he likes typing using the phonetic method.

I think Pinyin IM needs an option with 3 choices: "Only Simplified", "Only Traditional", "Both Simplified and Traditional". I think this last option is what is there now. This will make all such users happy.

Based on my limited knowledge, maybe the same option should exist for all Mandarin IMs, because each word can have simplified and traditional variants.

**Comment by wengxt** [comment]
The fcitx's own pinyin data is in simplified Chinese, and there is not plan changing that (Neither Traiditonal Chinese user or Simplified User would be happy if it's merged into same data). Using it to type Traiditonal Chinese for serious purpose is not recommended, because its traditional Chinese support is done by opencc/character mapping.

If you want real Traditional Chinese + Pinyin, please use rime. Its pinyin data is in Traditional Chinese.
