### ISSUE TITLE
Ubuntu 18.04 源中的 Fcitx (4.2.9.6) 与 Chromium/Chrome 输入交互不良

### ISSUE THREAD

**Issue by ghostplant** [fcitx/fcitx#405]
* ubuntu的版本为18.04
* fcitx 来自 apt: 4.2.9.6-1
* chromium 来自 apt: 64.0.3282

fcitx在chrome的任意文本框高速输入拼音时，有较高的概率会出现随机字母丢失在了fcitx-table框的外边，例如顺序输入zhongguo时候，fcitx-table可能接收到的输入为zhogguo，而n遗漏到chrome的文本框中。

经鉴定，同环境下ibus输入法在与chromium输入时没有此问题；

**Comment by wengxt** [comment]
install fcitx-frontend-gtk3

**Comment by ghostplant** [comment]
已经安装这个包了啊，问题并没有解决

**Comment by wengxt** [comment]
fcitx-diagnose 输出发一下

**Comment by ghostplant** [comment]
Can you reopen this issue?

**Comment by ghostplant** [comment]
[diagnose.txt](https://github.com/fcitx/fcitx/files/1788019/diagnose.txt)

**Comment by wengxt** [comment]
No, obviously it's a configuration issue.

If you're using im-config to set the env var, you'll also need fcitx-frontend-gtk2 (Although you might not use any gtk 2 app, the reason is gtk2/3 use different im module but they share the same env var, so unless both 2 and 3 im module for fcitx are detected, it will use xim as fallback).

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    **环境变量 GTK_IM_MODULE 的值被设为了 "xim" 而不是 "fcitx". 请检查您是否在某个初始化文件中错误的设置了它的值.**
    **您正在 gtk 程序中使用 xim.**

**Comment by ghostplant** [comment]
18.04的缺省设置就是这样的，的确没有装frontend-gtk2，不过16.04不装frontend-gtk2就没有这个问题。多谢！
