### ISSUE TITLE
Fcitx can't find KCModule on Kubuntu, even though it's insalled

### ISSUE THREAD

**Issue by metal450** [fcitx/fcitx#452]
I'm trying to get Japanese input (fcitx-mozc) setup on Kubuntu 20.04, but unfortunately nothing seems to be working as documented:

* If I launch "Fcitx Configuration," I get a dialog saying "You're currently running KDE, but KCModule for fcitx couldn't be found, the package name of this KCModule is usually kcm-fcitx or kde-config-fcitx."  **kde-config-fcitx is already installed** (and kcm-fcitx is not in the repo).
* According to tutorials like [this][1], there's supposed to be a config panel under System Settings->Regional->Input Method.  No such panel exists.
* Other tutorials have suggested installing fcitx-config-gtk3 (not in the repo) and/or fcitx-configtool (not in the repo).
* fcitx is already selected in im-config.

This was a fresh Kubuntu install, so I really wouldn't expect there to be any complications.  Below is the output of fcitx-diagnose - note:

* Regarding: "Cannot find a GUI config tool, please install one of `kcm-fcitx`, `fcitx-config-gtk2`, or `fcitx-config-gtk3`." None of those are available in the repo, but as mentioned, kde-config-fcitx is installed.
* Regarding: "Cannot find fcitx input method module for Qt4" & "Cannot find fcitx input method module for Qt5," According to https://wiki.archlinux.org/index.php/fcitx#Input_method_module, those are supposed to be fcitx-qt4 and fcitx-qt5. But neither of those are in the repo.

fcitx-diagnose:

# System Info:
1.  `uname -a`:

        Linux Latitude-5490-Kubuntu 5.4.42-050442-generic #202005200734 SMP Wed May 20 07:36:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID: Ubuntu
        Description:    Ubuntu 20.04 LTS
        Release:        20.04
        Codename:       focal

3.  `lsb_release -d`:

        Description:    Ubuntu 20.04 LTS

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=20.04
        DISTRIB_CODENAME=focal
        DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

5.  `/etc/os-release`:

        NAME="Ubuntu"
        VERSION="20.04 LTS (Focal Fossa)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu 20.04 LTS"
        VERSION_ID="20.04"
        HOME_URL="https://www.ubuntu.com/"
        SUPPORT_URL="https://help.ubuntu.com/"
        BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
        PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
        VERSION_CODENAME=focal
        UBUNTU_CODENAME=focal

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  Bash Version:

        BASH_VERSION='5.0.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+us+inet(evdev)"     };
                xkb_geometry  { include "pc(pc105)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            C.UTF-8
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=
            LC_CTYPE="C.UTF-8"
            LC_NUMERIC="C.UTF-8"
            LC_TIME="C.UTF-8"
            LC_COLLATE="C.UTF-8"
            LC_MONETARY="C.UTF-8"
            LC_MESSAGES="C.UTF-8"
            LC_PAPER="C.UTF-8"
            LC_NAME="C.UTF-8"
            LC_ADDRESS="C.UTF-8"
            LC_TELEPHONE="C.UTF-8"
            LC_MEASUREMENT="C.UTF-8"
            LC_IDENTIFICATION="C.UTF-8"
            LC_ALL=C.UTF-8

4.  Directories:

    1.  Home:

            /home/metal450

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/metal450/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/metal450/.config/fcitx`).

5.  Current user:

    The script is run as metal450 (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.9.7`

3.  process:

    Found 1 fcitx process:

           2530 fcitx <defunct>

4.  `fcitx-remote`:

    **Cannot connect to fcitx correctly.**

5.  DBus interface:

    Using `dbus-send` to check dbus.

    **Cannot find DBus name `org.fcitx.Fcitx` owner.**

    **Cannot find pid of DBus name `org.fcitx.Fcitx` owner.**

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    **Config GUI for gtk3 not found.**

4.  Config GUI for kde:

    **`kcmshell4` not found.**

    **Cannot find a GUI config tool, please install one of `kcm-fcitx`, `fcitx-config-gtk2`, or `fcitx-config-gtk3`.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **Cannot find xim_server on root window.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT4_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    **Cannot find fcitx input method module for Qt4.**
    **Cannot find fcitx input method module for Qt5.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.32` at `/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        Found fcitx im modules for gtk `2.24.32`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.24.18` at `/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.18

        Found fcitx im modules for gtk `3.24.18`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        **Gtk 2 immodule file /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so does not exist.**

    2.  gtk 3:

        **Gtk 3 immodule file /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so does not exist.**

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 12 enabled addons:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-clipboard
            fcitx-fullwidth-char
            fcitx-imselector
            fcitx-ipcportal
            fcitx-keyboard
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-spell
            fcitx-unicode

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    **Cannot find enabled fcitx user interface!**

## Input Methods:
1.  Found 1 enabled input methods:

        fcitx-keyboard-us

2.  Default input methods:

    You only have one keyboard input method enabled. You may want to add another input method to input other languages.

# Log:
1.  `date`:

        Sat May 23 13:20:19 PDT 2020

2.  `~/.config/fcitx/log/`:

        total 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` not found.
`

 [1]: https://www.ubuntubuzz.com/2017/09/kubuntu-writing-japanese-kanji-hiragana.html

**Comment by wengxt** [comment]
I doubt this could be a bug in upstream. You'd better check the right package that contains kcm-fcitx.so

**Comment by pineapple-cpp** [comment]
I had same problem in arch. After I install `fcitx-configtool`, it looks good.

**Comment by chadjoan** [comment]
Hello,

I just wanted to point out what's going on with this bug, and offer some solutions, just in case Google sends anyone else here.

This is definitely a bug in `fcitx-4`.

It looks like it might be fixed in `fcitx-5`, but I haven't had an opportunity to test it yet.

Notably, as of this writing, Gentoo's main package repository only has `fcitx` version 4. It looks like it would be possible to install version 5 using the `gentoo-zh` repository, which is fine, but less convenient, and I haven't gotten around to it.

## Workarounds: ##

#### Workaround #​1: Edit the fcitx-configtool script ####

It can be fixed by editing the `fcitx-configtool` script. Within the (uninstalled) fcitx project, it is at the path `data/script/fcitx-configtool.sh`. My system (Gentoo) seems to have installed this file to `/usr/bin/fcitx-configtool`.

Once that file is found/identified, find this line in the script:
```shell
if xprop -root KDE_SESSION_VERSION 2>&1 | grep -q "= 5"; then
```

It should be at line `109`.

Replace that line with this one:
```shell
if [ ! -z "${KDE_SESSION_VERSION##*[!0-9.+-]*}" ]; then
```

The replacement line is basically checking to see if the `$KDE_SESSION_VERSION` environment variable is numeric (and defined). It uses expansion logic to avoid BASH-isms when checking the number, and should thus be POSIX shell compatible. I'm borrowing the technique from this post: https://stackoverflow.com/a/2704760/1261963 . Though I also allow it to match '.', '+', and '-', so that slightly more complicated version numbers would still be recognized.

So far it is pretty reliable on my system (the newer one that had error come up). I tested it a few different ways:

* The check evaluates to `true` for my shell that's in a KDE environment (using Konsole), and it makes the script work when I click the "Configure" button on the systray popup. Good.

* It evaluates to `false` when I log in to the machine using an SSH session from another machine, and this is even the case when I log in as the user with an active KDE session (it still evaluates as `false`). Also good. (Because the remote SSH session is not part of the KDE session.)

* And it's still `false` from within my user's TTY. Good. (Because this is also outside of KDE; I'm referring to what you get when hitting `ctrl-alt-F1`.)

#### Workaround #​2: Use fixed fcitx fork ####

I made an even more comprehensive fix for this on my [fork](https://github.com/chadjoan/fcitx) of the `fcitx` project with [this commit](https://github.com/chadjoan/fcitx/commit/3b0f9a6be4f6a7ebd22444e4cda9e3415979354e).

Of course, _after_ writing that, I learned that I was working on the version 4 of `fcitx` which is being replaced by version 5 and no longer accepts pull requests. Hence I have decided not to make a pull request. And it looks like `fcitx-5` no longer uses `xprop` for KDE version detection, so it _should_ have fixed this already.

Nonetheless, I figured I'd at least publish my commit and mention it, since it might help people that are still running version 4 of fcitx.

Note that I haven't tried building that version from scratch, but instead just replaced the `fcitx-configtool.sh` script. I'd expect it to compile/install/whatever just fine, because most of the project is unmodified, but who knows. More importantly, the commit has [the fixed `fcitx-configtool.sh` file](https://github.com/chadjoan/fcitx/blob/3b0f9a6be4f6a7ebd22444e4cda9e3415979354e/data/script/fcitx-configtool.sh) in it, so anyone wishing to use it has the option of just installing their distro's normal version of `fcitx` (version 4) and then copying the fixed `fcitx-configtool.sh` file over it.

#### Workaround #​3: KDE System Settings, if available ####

Before I did any modifications to the `fcitx-configtool.sh` script, I tried a few other things, and some of those can be used to configure `fcitx` on a system where the script doesn't work.

Unlike the original poster, I _could_ go into KDE System Settings and then open these menus:
`[Personalization] Regional Settings -> Input Method`

This opened up the KDE+Qt configuration tool, with all of its goodies (select input methods, assign hotkeys under "Global Config", configure addons, etc).

Again, this was before I modified the `fcitx-configtool.sh` script, and at that time it was an interesting result, because it demonstrated to me that the KDE+Qt configuration tool was not only installed on my system (it was, and I knew that), but it even worked (which I hadn't seen yet on that system). It just couldn't be reached by the systray popup menu or the `fcitx-configtool` command.

#### Workaround #​4: Use GTK instead ####

There's also another workaround if GTK is available.

On Gentoo systems there is a package called `app-i18n/fcitx-configtool`, which is not installed by default when `app-i18n/fcitx` is installed. Despite it's name, it is NOT the `fcitx-configtool.sh` script from this project's repository. Instead, it is the GTK+ configuration tool for `fcitx`. This is its description, according to portage (the typical Gentoo package manager) :
`GTK+ GUI configuration tool for Fcitx`

Notably, if I install that `app-i18n/fcitx-configtool` package on my system, then the `fcitx-configtool.sh` script will open the GTK version of the `fcitx` configuration tool.

This is probably better than an error message.

It's still not correct behavior though.

That's because it is opening the wrong configuration tool. The `fcitx-configtool.sh` script should open the KDE+Qt configuration tool for `fcitx`, not use the GTK version.

But for anyone that needs this to work, can't patch the script, and doesn't mind if the user sees the wrong tool (it might be ugly or difficult to use when run from the KDE+Qt DE), then this could provide an alternative to the error message.


## The Cause: ##

The problem occurs at line `109` in `data/script/fcitx-configtool.sh`:
https://github.com/fcitx/fcitx/blob/15046e8b9f2c3b4ac1128d5b0cfeb65bf5ccec87/data/script/fcitx-configtool.sh

It's this line:
```shell
if xprop -root KDE_SESSION_VERSION 2>&1 | grep -q "= 5"; then
```

Before I wrote those fixes, I found that if I edit my system's instance of this script and remove that check, then I could successfully open the KDE configuration module for `fcitx`.

This works for both running `fcitx-configtool` and clicking "Configure" from the popup I get after right-clicking the input method icon in the systray.

I tried running that `xprop` command manually to see what the script was seeing, and it went like this:
```shell
$ xprop -root KDE_SESSION_VERSION 2>&1
KDE_SESSION_VERSION:  no such atom on any window.
```

Notably, this more trivial command seems to work as intended:
```shell
$ echo $KDE_SESSION_VERSION
5
```

Also, I have an older system where I get this result from the `xprop` query:
```
$ xprop -root KDE_SESSION_VERSION
KDE_SESSION_VERSION(CARDINAL) = 5
```
That output seems congruent with what the script expects, but it just doesn't work that way on the newer system.

This does make me worry that there could be some configuration on my (newer) system that I am missing. Unfortunately, I could not find ANY documentation on the KDE_SESSION_VERSION property. So it really isn't clear what would happen that would cause this to be absent on my machine, but present on the machine(s) of this scripts author(s) or on my older machine.

That said, I suspect it is more likely that the KDE_SESSION_VERSION window property isn't a standard/stable feature of KDE (hence why I couldn't find any documentation on it), but instead was some incidental implementation detail in an older version of KDE. And perhaps it was removed at some point, thus breaking the `fcitx-configtool.sh` script.

In my workaround I used the `$KDE_SESSION_VERSION` environment variable, which IS a standard feature of KDE, as documented here:
https://userbase.kde.org/KDE_System_Administration/Environment_Variables


## System Information: ##

Here is what the KDE "About" page reports about this system:
```
Operating System: Gentoo Linux 2.13
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.10
Kernel Version: 6.1.4-gentoo (64-bit)
Graphics Platform: X11
[...]
Graphics Processor: llvmpipe
```

In case it might be helpful to whoever might attempt to fix the script, I also ran `xprop -root` to get a list of all properties on the root "window" from the perspective of the shell that I test-ran `fcitx-configtool` from:
https://pastebin.com/D38uCPfy

Here is the KDE "About" page for my **older** system with the "working" `xprop -root KDE_SESSION_VERSION` command:
```
Operating System: Gentoo Linux 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.6.7-gentoo
OS Type: 64-bit
[...]
```

Because the file `kcm-fcitx.so` was mentioned, I decided to also run `locate kcm-fcitx.so` on both systems. And on both systems, this file does not exist. (And just to be paranoid, I can verify that my `locate` command is working by running something like `locate fcitx` and get plenty of results!)

I am not sure where that file would be located if it did exist (I have Google searched it, but no such luck). Regardless, it doesn't seem to correlate with whether the Qt configuration tool (and KCM) were installed or not; both of these systems have the KCM installed and also do not have this file. And with the fix(es) I mentioned earlier, `fcitx` (and its configuration) work fine with Qt+KDE, so I think the KCM module is there (on both of my systems), it just probably has a different name or something.

## End ##

Thank you.
