### ISSUE TITLE
Enchant >=2.1.3 not detected

### ISSUE THREAD

**Issue by Arfrever** [fcitx/fcitx#475]
Enchant >=2.1.3 (commit https://github.com/AbiWord/enchant/commit/8a853ad69ca8bd896723d86eea3e7573a8c11ebd) has some renames:
* Directory of headers: `enchant` -> `enchant-2`
* Library: `libenchant.so` -> `libenchant-2.so`
* Pkg-Config file: `enchant.pc` -> `enchant-2.pc`

Build system of Fcitx does not detect Enchant >=2.1.3:
```
-- Checking for module 'enchant'
--   No package 'enchant' found
-- Could NOT find Enchant (missing: ENCHANT_LIBRARIES ENCHANT_INCLUDE_DIR ENCHANT_API_COMPATIBLE)
```

(Fcitx 5 was fixed in different way in https://github.com/fcitx/fcitx5/commit/7e4fc275f51a9974947de6fd92aa093fbbba20c6.)

Fix for Fcitx 4: [fcitx-enchant.patch.txt](https://github.com/fcitx/fcitx/files/5520600/fcitx-enchant.patch.txt)

**Comment by ayalhw** [comment]
According to the information I got, This project seems to be no longer maintained, it is recommended to migrate to [fcitx5](https://github.com/fcitx/fcitx5).

**Comment by ayalhw** [comment]
（光速被打脸，溜了

**Comment by wengxt** [comment]
@ayalhw the problem is while we still commit some changes, but we don't have a good time frame to make new release (changes are infrequent and too small that would fit a new release). Having code here helps distro to cherry-pick fixes if they need to, but doesn't change that we're under maintenance only mode for fcitx 4.
