### ISSUE TITLE
Fcitx not working just for some windows in i3

### ISSUE THREAD

**Issue by Danielgb23** [fcitx/fcitx#506]
I have an Arch linux i3 system with the urxvt terminal emulator. But the fictix mandarin input only works for some or other terminal window with some rule I don't understand yet (it seems like it's only one terminal on the side of the window or something like that).

I can still type and the suggestions appear but when I press space (or enter) wathever I wrote doesn't goes to the input. It does for the "chosen" window though.

Edit: I think it's related to this because I have the positioning problem of the suggestion box too: 

https://wiki.archlinux.org/title/fcitx#Input_method_module 

But I have the packages for qt5 and qt4 installed

**Comment by wengxt** [comment]
Likely due to your configuration, please check https://fcitx-im.org/wiki/FAQ

**Comment by Danielgb23** [comment]
> Likely due to your configuration, please check https://fcitx-im.org/wiki/FAQ

Do you know how can I set up XIM only for a program like urxvt in the xinit?

**Comment by wengxt** [comment]
@Danielgb23 why would you want to do that?

You can create a script that set XMODIFIERS and launch urxvt and always use that script to launch urxvt.

**Comment by Danielgb23** [comment]
> @Danielgb23 why would you want to do that?
For what I understand from here:
https://wiki.archlinux.org/title/fcitx#Input_method_module

urxvt is a non GTK/Qt input application and the FAQ you linked says you should use XIM for that. But also that it should be avoided when not necessary.

>You can create a script that set XMODIFIERS and launch urxvt and always use that script to launch urxvt.
Like:
```
#!/bin/bash
export XMODIFIERS=@im=xim
urxvt
```
Wouldn't this mess with the configuration of other programs when I set the variable?

**Comment by wengxt** [comment]
What the doc actually mean is that, if you have a way to avoid using XIM for input method (Gtk23 / Qt4 has XIM support, but also provides third party im module support via a plugin system), you should consider do that.

If you need to use XIM with non-gtk/qt X11 application, you need to set it anyway.

Following is what most people set when using fcitx
```
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```

Hope that clarifies it a little bit.
See https://fcitx-im.org/wiki/Input_method_related_environment_variables and  https://fcitx-im.org/wiki/Configure_(Other)

**Comment by wengxt** [comment]
When Gtk/Qt env variable is set, gtk/qt application will not use XIM anyway, if that's what you're concerning. Simply set it globally and you're done.

**Comment by Danielgb23** [comment]
I have that

> export XMODIFIERS=@im=fcitx
> export GTK_IM_MODULE=fcitx
> export QT_IM_MODULE=fcitx

I have that set up. And it works. My problem is that when I have two or more i3 windows in the same screen specifically as tiles only one works. Either the left most or the right most. I also get the suggestion box all the way down far from the actual input. But only for urxvt. For chromium it works fine

**Comment by Danielgb23** [comment]
I ran `urxvt` from other terminal and I got this error message:

`urxvt: unable to create fontset for input method, try "-pt Root". Continuing.
`
I think that might be the issue

**Comment by wengxt** [comment]
Yeah, that's basically some what related to XIM. If you can read Chinese, you might find this emacs bug interesting: https://www.csslayer.info/wordpress/fcitx-dev/%e4%b8%96%e7%ba%aa%e6%9c%aa%e8%a7%a3%e4%b9%8b%e8%b0%9c%e4%b9%8b-emacs-%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e8%ae%be%e7%bd%ae-lc_ctype-%e6%89%8d%e8%83%bd%e7%94%a8%e8%be%93%e5%85%a5%e6%b3%95%e7%bb%88/

The XFontSet passed to XIM protocol is merely an obsolete thing that actually no modern input method cares about. Applications like xterm/urxvt/emacs from old days may still do that, and that part of relevant logic is pretty fragile in existing implementations.

For example, the emacs bug above is triggered by the code find too many fonts. It can be either happen to you if urxvt fails to find any fonts or whatever (NOTE, even though fcitx or ibus or whatever input method framework you know about doesn't care about this font information, it's just part of protocol that these applications choose to implement).

There are certain workaround like enforce a LC_CTYPE=zh_CN.UTF-8 to make the font find by the code to be more or less as documented by the FAQ, or install some font might help. https://fcitx-im.org/wiki/FAQ#Emacs

The suggestion box part, might be due to for some reason urxvt chose to use a xim style that doesn't send suggestion box location. XIM Style is chosen based one some negotiation between application and input method, but fcitx always declare it support over-the-spot style.

At this point, you might get why FAQ is saying avoid XIM if "possible". It's just an protocol that is too old that no one ever maintain it anymore and has lots of out-of-date part.

I'm not saying you should try another terminal emulator, but using a different one might be less trouble some for all these problems. If you're looking for a non-gtk/qt one, I'd recommend xterm/alacritty.

Though xterm/alacritty also uses XIM, but I've never seen xterm have similar issue so I just assume it's implementation is quite robust. As for alacritty, it seems to be quite popular among the other fcitx users I know, so likely it's also a good one.

**Comment by Danielgb23** [comment]
> There are certain workaround like enforce a LC_CTYPE=zh_CN.UTF-8 to make the font find by the code to
That doens't work unfortunately. I used:
```
#!/bin/bash
export LC_CTYPE=zh_CN.utf8 urxvt
urxvt

```
```
locale -a 
...
zh_CN.utf8
```

It's been hard finding a good terminal with all the features I want. Kitty isn't transparent in i3, doens't work well with w3m, doens't support fcitx. Urxvt has this issue. Alacrity and xterm don't have tabs unless you use tmux...

**Comment by wengxt** [comment]
@Danielgb23 as for kitty, if you use fcitx5, you can use it with GLFW_IM_MODULE=ibus
I personally like konsole as I use KDE?

**Comment by Danielgb23** [comment]
Do you know any input method that works well with urxvt? I liked it best so far

**Comment by wengxt** [comment]
@Danielgb23 as I mentioned before, it does not really matter for what input method framework you use, the issue is within urxvt that does not handling some corner case well.

Can you show me your urxvt config, I can tried to reproduce and see if I can find a way to make it work for you.

Also please attach the output of `xlsfonts`

**Comment by Danielgb23** [comment]
```
!execute to reload:
!xrdb ~/.Xresources
!xrdb -merge ~/.Xresources

URxvt.scrollBar: false

URxvt*font: xft:Dejavu Sans Mono:size=12, xft:Source Han Sans CN
URxvt.inputMethod:fcitx

urxvt*transparent: true
urxvt*shading: 15

urxvt*foreground: white
urxvt*background: black

!dark gray
*color0:  #2E3436
!bright red
*color1:  #a40000
!light green
*color2:  #4E9A06
!gold
*color3:  #C4A000
!blue
*color4:  #3465A4
!purple
*color5:  #75507B
!orange
*color6:  #ce5c00
!light gray
*color7:  #babdb9
!dark gray
*color8:  #555753
!red
*color9:  #EF2929
!lime
*color10: #8AE234
!yellow
*color11: #FCE94F
!light blue
*color12: #729FCF
!purple
*color13: #AD7FA8
!orange
*color14: #fcaf3e
!white
*color15: #EEEEEC

URxvt.tabbed.tabbar-fg: 2
URxvt.tabbed.tabbar-bg: 0
URxvt.tabbed.tab-fg: 4
URxvt.tabbed.tab-bg: 0

!Perl extensions
URxvt.perl-ext-common: default,matcher,tabbed

!URLs 
URxvt.matcher.rend.0:  Bold Uline fg6 
URxvt.matcher.button: 1
URxvt.url-launcher: /usr/bin/chromium
URxvt.underlineURLs: true

!copy-paste
URxvt.iso14755: False
URxvt.iso14755_52: false
URxvt.keysym.Shift-Control-V: eval:paste_clipboard
URxvt.keysym.Shift-Control-C: eval:selection_to_clipboard

!scroll output
URxvt.keysym.Shift-PageUP: command:\033]720;1\007
URxvt.keysym.Shift-PageDown: command:\033]721;1\007

```


```
$ xlsfonts
-misc-fixed-medium-r-semicondensed--0-0-75-75-c-0-iso8859-1
-misc-fixed-medium-r-semicondensed--13-100-100-100-c-60-iso8859-1
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1
6x13
cursor
fixed

```

**Comment by wengxt** [comment]
Hi, I tried your urxvt config, and found that when you enabled "tabbed", input method would not initially work here.
I assume that's certainly a urxvt issue.

I have to click within the urxvt window and then it start to work. I think it's some what related to Focus handling in urxvt.

Also I suggest that you add following line in your config:

URxvt.preeditType: OverTheSpot
